# Generated by Django 4.0.4 on 2022-05-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='scholarships',
        ),
    ]
