# Generated by Django 4.0.4 on 2022-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_project_scholarships'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='content',
            field=models.CharField(default=str, max_length=150),
            preserve_default=False,
        ),
    ]
