# Generated by Django 4.0.4 on 2022-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_scholarships_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='content',
            field=models.TextField(max_length=150),
        ),
    ]
