# Generated by Django 4.0.4 on 2022-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_academic_level',
            name='year_of_admission',
            field=models.PositiveIntegerField(),
        ),
    ]
