# Generated by Django 4.0.4 on 2022-05-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_current_academic_level_year_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
