# Generated by Django 4.1.3 on 2022-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_alter_bio_data_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='next_of_kin',
            old_name='NEXT_OF_KIN_ADDRESS',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='next_of_kin',
            old_name='NEXT_OF_KIN_EMAIL',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='next_of_kin',
            old_name='NEXT_OF_KIN_NAME',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='next_of_kin',
            old_name='NEXT_OF_KIN_OCCUPATION',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='next_of_kin',
            old_name='NEXT_OF_KIN_PHONE_NUMBER',
            new_name='relationship',
        ),
        migrations.RemoveField(
            model_name='next_of_kin',
            name='NEXT_OF_KIN_RELATIONSHIP',
        ),
        migrations.AddField(
            model_name='next_of_kin',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
