# Generated by Django 4.1.3 on 2022-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_h',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_w',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='image_h', upload_to='profile', width_field='image_w'),
        ),
    ]
