# Generated by Django 4.1.3 on 2022-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_profile_image_h_profile_image_w_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_h',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_w',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
