# Generated by Django 4.1.3 on 2022-11-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0011_remove_profile_image_h_remove_profile_image_w_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='team',
        ),
    ]
